# -*- coding: utf-8 -*-
"""Stock Price Visualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16-Pu-bUhXjwoe7WAYoNNmwc-6kAMdrdU
"""

import pandas as pd

data = {
    "Date": ["2023-01-01","2023-01-02","2023-01-03","2023-01-04","2023-01-05",
             "2023-01-06","2023-01-07","2023-01-08","2023-01-09","2023-01-10"],
    "Tesla": [123,125,128,130,129,135,138,140,142,145],
    "Apple": [135,137,139,140,138,141,142,145,146,147]
}
df = pd.DataFrame(data)
df.to_csv("stock_data.csv", index=False)
print("CSV file created!")

# stock_price_visualization.py
# Compare Tesla and Apple stock prices using Python

import pandas as pd
import matplotlib.pyplot as plt

# Read dataset
df = pd.read_csv("stock_data.csv")

# Ensure Date is datetime type
df["Date"] = pd.to_datetime(df["Date"])

# Plot Tesla vs Apple
plt.figure(figsize=(10,6))
plt.plot(df["Date"], df["Tesla"], label="Tesla", color="red")
plt.plot(df["Date"], df["Apple"], label="Apple", color="blue")
plt.title("Tesla vs Apple Stock Prices")
plt.xlabel("Date")
plt.ylabel("Stock Price (USD)")
plt.legend()
plt.tight_layout()
plt.savefig("stock_comparison.png")
plt.show()

# Save cleaned data
df.to_csv("cleaned_stock_data.csv", index=False)

readme_text = """# Stock Price Visualization (Python Project)

A simple project that compares the stock prices of **Tesla** and **Apple** over time using Python.

---

## 📂 Files
- stock_price_visualization.py → Main script
- stock_data.csv → Example dataset
- stock_comparison.png → Output graph (generated after running the script)
- cleaned_stock_data.csv → Cleaned dataset (generated)

---

## ▶️ How to Run
1. Install required libraries:
pip install pandas matplotlib

2. Run the script:
python stock_price_visualization.py

---

## 📊 Example Output
The project generates a line chart comparing Tesla and Apple stock prices.

![Stock Comparison](stock_comparison.png)

---

## 🔑 Learning Outcomes
- Reading and cleaning CSV files with Pandas
- Converting dates to proper datetime format
- Plotting multiple time-series with Matplotlib
- Comparing trends between two datasets
"""

with open("README.md", "w") as f:
    f.write(readme_text)

print("README.md created successfully!")

from google.colab import files
files.download("README.md")